// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package verification

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FieldType int32

const (
	FieldType_UNKNOWN_FIELD_TYPE FieldType = 0
	FieldType_RAW                FieldType = 1
	FieldType_ERROR              FieldType = 2
	FieldType_EMAIL              FieldType = 16
	FieldType_NAME               FieldType = 17
	FieldType_PASSWORD           FieldType = 18
	FieldType_COUNTRY            FieldType = 19
	FieldType_REGION             FieldType = 20
	FieldType_CITY               FieldType = 21
	FieldType_STREET             FieldType = 22
	FieldType_BUILDING           FieldType = 23
	FieldType_APARTMENT          FieldType = 24
	FieldType_ROOM               FieldType = 25
	FieldType_EXISTING_USER      FieldType = 26
	FieldType_EXISTING_PROPERTY  FieldType = 27
	FieldType_USER_LOGIN         FieldType = 28
	FieldType_FULL_ADDRESS       FieldType = 29
)

var FieldType_name = map[int32]string{
	0:  "UNKNOWN_FIELD_TYPE",
	1:  "RAW",
	2:  "ERROR",
	16: "EMAIL",
	17: "NAME",
	18: "PASSWORD",
	19: "COUNTRY",
	20: "REGION",
	21: "CITY",
	22: "STREET",
	23: "BUILDING",
	24: "APARTMENT",
	25: "ROOM",
	26: "EXISTING_USER",
	27: "EXISTING_PROPERTY",
	28: "USER_LOGIN",
	29: "FULL_ADDRESS",
}

var FieldType_value = map[string]int32{
	"UNKNOWN_FIELD_TYPE": 0,
	"RAW":                1,
	"ERROR":              2,
	"EMAIL":              16,
	"NAME":               17,
	"PASSWORD":           18,
	"COUNTRY":            19,
	"REGION":             20,
	"CITY":               21,
	"STREET":             22,
	"BUILDING":           23,
	"APARTMENT":          24,
	"ROOM":               25,
	"EXISTING_USER":      26,
	"EXISTING_PROPERTY":  27,
	"USER_LOGIN":         28,
	"FULL_ADDRESS":       29,
}

func (x FieldType) String() string {
	return proto.EnumName(FieldType_name, int32(x))
}

func (FieldType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type Validity int32

const (
	Validity_UNKNOWN_VALIDITY Validity = 0
	Validity_VALID            Validity = 1
	Validity_INVALID          Validity = 2
)

var Validity_name = map[int32]string{
	0: "UNKNOWN_VALIDITY",
	1: "VALID",
	2: "INVALID",
}

var Validity_value = map[string]int32{
	"UNKNOWN_VALIDITY": 0,
	"VALID":            1,
	"INVALID":          2,
}

func (x Validity) String() string {
	return proto.EnumName(Validity_name, int32(x))
}

func (Validity) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

type Component struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Primitive            *PrimitiveDescription `protobuf:"bytes,2,opt,name=primitive,proto3" json:"primitive,omitempty"`
	Complex              *StructDescription    `protobuf:"bytes,3,opt,name=complex,proto3" json:"complex,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Component) Reset()         { *m = Component{} }
func (m *Component) String() string { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()    {}
func (*Component) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Component) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Component.Unmarshal(m, b)
}
func (m *Component) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Component.Marshal(b, m, deterministic)
}
func (m *Component) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Component.Merge(m, src)
}
func (m *Component) XXX_Size() int {
	return xxx_messageInfo_Component.Size(m)
}
func (m *Component) XXX_DiscardUnknown() {
	xxx_messageInfo_Component.DiscardUnknown(m)
}

var xxx_messageInfo_Component proto.InternalMessageInfo

func (m *Component) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Component) GetPrimitive() *PrimitiveDescription {
	if m != nil {
		return m.Primitive
	}
	return nil
}

func (m *Component) GetComplex() *StructDescription {
	if m != nil {
		return m.Complex
	}
	return nil
}

type PrimitiveDescription struct {
	Type                 FieldType             `protobuf:"varint,1,opt,name=type,proto3,enum=mashroom.verification.FieldType" json:"type,omitempty"`
	Text                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Integer              *wrappers.Int64Value  `protobuf:"bytes,3,opt,name=integer,proto3" json:"integer,omitempty"`
	Fraction             *wrappers.DoubleValue `protobuf:"bytes,4,opt,name=fraction,proto3" json:"fraction,omitempty"`
	Binary               *wrappers.BytesValue  `protobuf:"bytes,5,opt,name=binary,proto3" json:"binary,omitempty"`
	Boolean              *wrappers.BoolValue   `protobuf:"bytes,6,opt,name=boolean,proto3" json:"boolean,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PrimitiveDescription) Reset()         { *m = PrimitiveDescription{} }
func (m *PrimitiveDescription) String() string { return proto.CompactTextString(m) }
func (*PrimitiveDescription) ProtoMessage()    {}
func (*PrimitiveDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *PrimitiveDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrimitiveDescription.Unmarshal(m, b)
}
func (m *PrimitiveDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrimitiveDescription.Marshal(b, m, deterministic)
}
func (m *PrimitiveDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrimitiveDescription.Merge(m, src)
}
func (m *PrimitiveDescription) XXX_Size() int {
	return xxx_messageInfo_PrimitiveDescription.Size(m)
}
func (m *PrimitiveDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_PrimitiveDescription.DiscardUnknown(m)
}

var xxx_messageInfo_PrimitiveDescription proto.InternalMessageInfo

func (m *PrimitiveDescription) GetType() FieldType {
	if m != nil {
		return m.Type
	}
	return FieldType_UNKNOWN_FIELD_TYPE
}

func (m *PrimitiveDescription) GetText() *wrappers.StringValue {
	if m != nil {
		return m.Text
	}
	return nil
}

func (m *PrimitiveDescription) GetInteger() *wrappers.Int64Value {
	if m != nil {
		return m.Integer
	}
	return nil
}

func (m *PrimitiveDescription) GetFraction() *wrappers.DoubleValue {
	if m != nil {
		return m.Fraction
	}
	return nil
}

func (m *PrimitiveDescription) GetBinary() *wrappers.BytesValue {
	if m != nil {
		return m.Binary
	}
	return nil
}

func (m *PrimitiveDescription) GetBoolean() *wrappers.BoolValue {
	if m != nil {
		return m.Boolean
	}
	return nil
}

type FieldDescription struct {
	Name                 string                `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Primitive            *PrimitiveDescription `protobuf:"bytes,2,opt,name=primitive,proto3" json:"primitive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FieldDescription) Reset()         { *m = FieldDescription{} }
func (m *FieldDescription) String() string { return proto.CompactTextString(m) }
func (*FieldDescription) ProtoMessage()    {}
func (*FieldDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *FieldDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FieldDescription.Unmarshal(m, b)
}
func (m *FieldDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FieldDescription.Marshal(b, m, deterministic)
}
func (m *FieldDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FieldDescription.Merge(m, src)
}
func (m *FieldDescription) XXX_Size() int {
	return xxx_messageInfo_FieldDescription.Size(m)
}
func (m *FieldDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_FieldDescription.DiscardUnknown(m)
}

var xxx_messageInfo_FieldDescription proto.InternalMessageInfo

func (m *FieldDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *FieldDescription) GetPrimitive() *PrimitiveDescription {
	if m != nil {
		return m.Primitive
	}
	return nil
}

type VerifyFieldResult struct {
	Validity             Validity          `protobuf:"varint,1,opt,name=validity,proto3,enum=mashroom.verification.Validity" json:"validity,omitempty"`
	Components           []*Component      `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	Description          *FieldDescription `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VerifyFieldResult) Reset()         { *m = VerifyFieldResult{} }
func (m *VerifyFieldResult) String() string { return proto.CompactTextString(m) }
func (*VerifyFieldResult) ProtoMessage()    {}
func (*VerifyFieldResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *VerifyFieldResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyFieldResult.Unmarshal(m, b)
}
func (m *VerifyFieldResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyFieldResult.Marshal(b, m, deterministic)
}
func (m *VerifyFieldResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyFieldResult.Merge(m, src)
}
func (m *VerifyFieldResult) XXX_Size() int {
	return xxx_messageInfo_VerifyFieldResult.Size(m)
}
func (m *VerifyFieldResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyFieldResult.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyFieldResult proto.InternalMessageInfo

func (m *VerifyFieldResult) GetValidity() Validity {
	if m != nil {
		return m.Validity
	}
	return Validity_UNKNOWN_VALIDITY
}

func (m *VerifyFieldResult) GetComponents() []*Component {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *VerifyFieldResult) GetDescription() *FieldDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

type StructDescription struct {
	Name                 string              `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields               []*FieldDescription `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *StructDescription) Reset()         { *m = StructDescription{} }
func (m *StructDescription) String() string { return proto.CompactTextString(m) }
func (*StructDescription) ProtoMessage()    {}
func (*StructDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *StructDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StructDescription.Unmarshal(m, b)
}
func (m *StructDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StructDescription.Marshal(b, m, deterministic)
}
func (m *StructDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StructDescription.Merge(m, src)
}
func (m *StructDescription) XXX_Size() int {
	return xxx_messageInfo_StructDescription.Size(m)
}
func (m *StructDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_StructDescription.DiscardUnknown(m)
}

var xxx_messageInfo_StructDescription proto.InternalMessageInfo

func (m *StructDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StructDescription) GetFields() []*FieldDescription {
	if m != nil {
		return m.Fields
	}
	return nil
}

type VerifyStructResult struct {
	Validity             Validity             `protobuf:"varint,1,opt,name=validity,proto3,enum=mashroom.verification.Validity" json:"validity,omitempty"`
	Components           []*Component         `protobuf:"bytes,2,rep,name=components,proto3" json:"components,omitempty"`
	FieldResults         []*VerifyFieldResult `protobuf:"bytes,3,rep,name=field_results,json=fieldResults,proto3" json:"field_results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VerifyStructResult) Reset()         { *m = VerifyStructResult{} }
func (m *VerifyStructResult) String() string { return proto.CompactTextString(m) }
func (*VerifyStructResult) ProtoMessage()    {}
func (*VerifyStructResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *VerifyStructResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyStructResult.Unmarshal(m, b)
}
func (m *VerifyStructResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyStructResult.Marshal(b, m, deterministic)
}
func (m *VerifyStructResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyStructResult.Merge(m, src)
}
func (m *VerifyStructResult) XXX_Size() int {
	return xxx_messageInfo_VerifyStructResult.Size(m)
}
func (m *VerifyStructResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyStructResult.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyStructResult proto.InternalMessageInfo

func (m *VerifyStructResult) GetValidity() Validity {
	if m != nil {
		return m.Validity
	}
	return Validity_UNKNOWN_VALIDITY
}

func (m *VerifyStructResult) GetComponents() []*Component {
	if m != nil {
		return m.Components
	}
	return nil
}

func (m *VerifyStructResult) GetFieldResults() []*VerifyFieldResult {
	if m != nil {
		return m.FieldResults
	}
	return nil
}

type VerifyPostcodeRequest struct {
	Postcode             string   `protobuf:"bytes,1,opt,name=postcode,proto3" json:"postcode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPostcodeRequest) Reset()         { *m = VerifyPostcodeRequest{} }
func (m *VerifyPostcodeRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyPostcodeRequest) ProtoMessage()    {}
func (*VerifyPostcodeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *VerifyPostcodeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPostcodeRequest.Unmarshal(m, b)
}
func (m *VerifyPostcodeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPostcodeRequest.Marshal(b, m, deterministic)
}
func (m *VerifyPostcodeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPostcodeRequest.Merge(m, src)
}
func (m *VerifyPostcodeRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyPostcodeRequest.Size(m)
}
func (m *VerifyPostcodeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPostcodeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPostcodeRequest proto.InternalMessageInfo

func (m *VerifyPostcodeRequest) GetPostcode() string {
	if m != nil {
		return m.Postcode
	}
	return ""
}

type VerifyPostcodeQueryRequest struct {
	QueryLine            string   `protobuf:"bytes,1,opt,name=queryLine,proto3" json:"queryLine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPostcodeQueryRequest) Reset()         { *m = VerifyPostcodeQueryRequest{} }
func (m *VerifyPostcodeQueryRequest) String() string { return proto.CompactTextString(m) }
func (*VerifyPostcodeQueryRequest) ProtoMessage()    {}
func (*VerifyPostcodeQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *VerifyPostcodeQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPostcodeQueryRequest.Unmarshal(m, b)
}
func (m *VerifyPostcodeQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPostcodeQueryRequest.Marshal(b, m, deterministic)
}
func (m *VerifyPostcodeQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPostcodeQueryRequest.Merge(m, src)
}
func (m *VerifyPostcodeQueryRequest) XXX_Size() int {
	return xxx_messageInfo_VerifyPostcodeQueryRequest.Size(m)
}
func (m *VerifyPostcodeQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPostcodeQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPostcodeQueryRequest proto.InternalMessageInfo

func (m *VerifyPostcodeQueryRequest) GetQueryLine() string {
	if m != nil {
		return m.QueryLine
	}
	return ""
}

type VerifyPostcodeResult struct {
	City                 string   `protobuf:"bytes,1,opt,name=city,proto3" json:"city,omitempty"`
	AddressLine          []string `protobuf:"bytes,2,rep,name=addressLine,proto3" json:"addressLine,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerifyPostcodeResult) Reset()         { *m = VerifyPostcodeResult{} }
func (m *VerifyPostcodeResult) String() string { return proto.CompactTextString(m) }
func (*VerifyPostcodeResult) ProtoMessage()    {}
func (*VerifyPostcodeResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *VerifyPostcodeResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyPostcodeResult.Unmarshal(m, b)
}
func (m *VerifyPostcodeResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyPostcodeResult.Marshal(b, m, deterministic)
}
func (m *VerifyPostcodeResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyPostcodeResult.Merge(m, src)
}
func (m *VerifyPostcodeResult) XXX_Size() int {
	return xxx_messageInfo_VerifyPostcodeResult.Size(m)
}
func (m *VerifyPostcodeResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyPostcodeResult.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyPostcodeResult proto.InternalMessageInfo

func (m *VerifyPostcodeResult) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *VerifyPostcodeResult) GetAddressLine() []string {
	if m != nil {
		return m.AddressLine
	}
	return nil
}

func init() {
	proto.RegisterEnum("mashroom.verification.FieldType", FieldType_name, FieldType_value)
	proto.RegisterEnum("mashroom.verification.Validity", Validity_name, Validity_value)
	proto.RegisterType((*Component)(nil), "mashroom.verification.Component")
	proto.RegisterType((*PrimitiveDescription)(nil), "mashroom.verification.PrimitiveDescription")
	proto.RegisterType((*FieldDescription)(nil), "mashroom.verification.FieldDescription")
	proto.RegisterType((*VerifyFieldResult)(nil), "mashroom.verification.VerifyFieldResult")
	proto.RegisterType((*StructDescription)(nil), "mashroom.verification.StructDescription")
	proto.RegisterType((*VerifyStructResult)(nil), "mashroom.verification.VerifyStructResult")
	proto.RegisterType((*VerifyPostcodeRequest)(nil), "mashroom.verification.VerifyPostcodeRequest")
	proto.RegisterType((*VerifyPostcodeQueryRequest)(nil), "mashroom.verification.VerifyPostcodeQueryRequest")
	proto.RegisterType((*VerifyPostcodeResult)(nil), "mashroom.verification.VerifyPostcodeResult")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 899 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0x5d, 0x73, 0x22, 0x45,
	0x14, 0x5d, 0x02, 0x0b, 0xcc, 0x25, 0x49, 0x35, 0x77, 0x93, 0x15, 0xd9, 0xa8, 0x14, 0x2f, 0xc6,
	0x5d, 0x05, 0x4d, 0xa2, 0xae, 0xfa, 0xa0, 0x24, 0x4c, 0x52, 0x53, 0xc2, 0x80, 0xcd, 0x40, 0x8c,
	0x2f, 0x38, 0x0c, 0x0d, 0x3b, 0x95, 0x61, 0x7a, 0x32, 0xd3, 0xc4, 0xf0, 0xa7, 0xfc, 0x0d, 0xfe,
	0x0e, 0xab, 0x7c, 0xf1, 0x77, 0xf8, 0x60, 0xcd, 0x17, 0x99, 0x6c, 0x42, 0x0a, 0x1f, 0xac, 0xda,
	0xb7, 0xee, 0xae, 0x73, 0xee, 0xb9, 0xf7, 0x70, 0x2e, 0x03, 0x92, 0xee, 0x98, 0x35, 0xc7, 0xe5,
	0x82, 0xe3, 0xee, 0x4c, 0xf7, 0xde, 0xb8, 0x9c, 0xcf, 0x6a, 0xd7, 0xcc, 0x35, 0x27, 0xa6, 0xa1,
	0x0b, 0x93, 0xdb, 0xe5, 0x0f, 0xa7, 0x9c, 0x4f, 0x2d, 0x56, 0x0f, 0x40, 0xa3, 0xf9, 0xa4, 0xfe,
	0x9b, 0xab, 0x3b, 0x0e, 0x73, 0xbd, 0x90, 0x56, 0xfd, 0x3d, 0x05, 0xd2, 0x09, 0x9f, 0x39, 0xdc,
	0x66, 0xb6, 0x40, 0x84, 0x8c, 0xad, 0xcf, 0x58, 0x29, 0x55, 0x49, 0xed, 0x4b, 0x34, 0x38, 0xa3,
	0x02, 0x92, 0xe3, 0x9a, 0x33, 0x53, 0x98, 0xd7, 0xac, 0xb4, 0x51, 0x49, 0xed, 0x17, 0x0e, 0x5e,
	0xd5, 0x1e, 0x14, 0xab, 0x75, 0x63, 0x5c, 0x93, 0x79, 0x86, 0x6b, 0x3a, 0xfe, 0x23, 0xbd, 0x65,
	0xe3, 0x31, 0xe4, 0x0c, 0x3e, 0x73, 0x2c, 0x76, 0x53, 0x4a, 0x07, 0x85, 0xf6, 0x57, 0x14, 0xea,
	0x09, 0x77, 0x6e, 0x88, 0x64, 0x95, 0x98, 0x58, 0xfd, 0x73, 0x03, 0x76, 0x1e, 0xd2, 0xc1, 0x23,
	0xc8, 0x88, 0x85, 0x13, 0xf6, 0xbe, 0x7d, 0x50, 0x59, 0x51, 0xf9, 0xd4, 0x64, 0xd6, 0x58, 0x5b,
	0x38, 0x8c, 0x06, 0x68, 0xfc, 0x1c, 0x32, 0x82, 0xdd, 0x88, 0x68, 0xb0, 0xbd, 0x5a, 0x68, 0x57,
	0x2d, 0xb6, 0xcb, 0xef, 0xc4, 0xb4, 0xa7, 0x03, 0xdd, 0x9a, 0xfb, 0x0c, 0x76, 0x23, 0xf0, 0x4b,
	0xc8, 0x99, 0xb6, 0x60, 0x53, 0xe6, 0x46, 0x43, 0xbc, 0xb8, 0x47, 0x52, 0x6c, 0xf1, 0xd5, 0x51,
	0xc8, 0x89, 0xb1, 0xf8, 0x1a, 0xf2, 0x13, 0x57, 0x37, 0xfc, 0x26, 0x4a, 0x99, 0x15, 0x62, 0x4d,
	0x3e, 0x1f, 0x59, 0x2c, 0x24, 0x2e, 0xd1, 0x78, 0x08, 0xd9, 0x91, 0x69, 0xeb, 0xee, 0xa2, 0xf4,
	0x74, 0x85, 0xde, 0xf1, 0x42, 0x30, 0x2f, 0xa4, 0x45, 0x50, 0x3c, 0x82, 0xdc, 0x88, 0x73, 0x8b,
	0xe9, 0x76, 0x29, 0x1b, 0xb0, 0xca, 0xf7, 0x59, 0x9c, 0x5b, 0x51, 0x93, 0x11, 0xb4, 0x7a, 0x05,
	0x24, 0x30, 0x28, 0xe9, 0xeb, 0xff, 0x9b, 0x89, 0xea, 0x5f, 0x29, 0x28, 0x0e, 0x7c, 0xc2, 0x22,
	0x50, 0xa6, 0xcc, 0x9b, 0x5b, 0x02, 0xbf, 0x83, 0xfc, 0xb5, 0x6e, 0x99, 0x63, 0x53, 0x2c, 0xa2,
	0x1f, 0xf4, 0xa3, 0x15, 0xf5, 0x07, 0x11, 0x8c, 0x2e, 0x09, 0xf8, 0x03, 0x80, 0x11, 0x47, 0xda,
	0x2b, 0x6d, 0x54, 0xd2, 0xfb, 0x85, 0x95, 0x79, 0x58, 0x66, 0x9f, 0x26, 0x38, 0xa8, 0x40, 0x61,
	0x7c, 0xdb, 0x6e, 0xf4, 0x3b, 0x7f, 0xfc, 0x58, 0xa4, 0x92, 0xd3, 0x25, 0xb9, 0xd5, 0x37, 0x50,
	0xbc, 0x97, 0xe6, 0x07, 0x3d, 0xfd, 0x1e, 0xb2, 0x13, 0xbf, 0x52, 0xdc, 0xf1, 0xda, 0x72, 0x11,
	0xad, 0xfa, 0x77, 0x0a, 0x30, 0x74, 0x32, 0x14, 0x7c, 0x37, 0xac, 0x6c, 0xc3, 0x56, 0xd0, 0xdf,
	0xd0, 0x0d, 0xda, 0xf1, 0x4a, 0xe9, 0xa0, 0xc8, 0xaa, 0xcd, 0xbf, 0x17, 0x05, 0xba, 0x39, 0xb9,
	0xbd, 0x78, 0xd5, 0x43, 0xd8, 0x0d, 0x21, 0x5d, 0xee, 0x09, 0x83, 0x8f, 0x19, 0x65, 0x57, 0x73,
	0xe6, 0x09, 0x2c, 0x43, 0xde, 0x89, 0x9e, 0x22, 0x5b, 0x97, 0xf7, 0xea, 0xb7, 0x50, 0xbe, 0x4b,
	0xfa, 0x69, 0xce, 0xdc, 0x45, 0xcc, 0xdc, 0x03, 0xe9, 0xca, 0xbf, 0xb7, 0x4c, 0x3b, 0xa6, 0xde,
	0x3e, 0x54, 0x5b, 0xb0, 0xf3, 0xb6, 0x60, 0x60, 0x2b, 0x42, 0xc6, 0x88, 0x2d, 0x95, 0x68, 0x70,
	0xc6, 0x0a, 0x14, 0xf4, 0xf1, 0xd8, 0x65, 0x9e, 0x17, 0xd4, 0xf2, 0xed, 0x92, 0x68, 0xf2, 0xe9,
	0xe5, 0x3f, 0x29, 0x90, 0x96, 0x7f, 0x41, 0xf8, 0x1c, 0xb0, 0xaf, 0xfe, 0xa8, 0x76, 0xce, 0xd5,
	0xe1, 0xa9, 0x22, 0xb7, 0x9a, 0x43, 0xed, 0xa2, 0x2b, 0x93, 0x27, 0x98, 0x83, 0x34, 0x6d, 0x9c,
	0x93, 0x14, 0x4a, 0xf0, 0x54, 0xa6, 0xb4, 0x43, 0xc9, 0x46, 0x70, 0x6c, 0x37, 0x94, 0x16, 0x21,
	0x98, 0x87, 0x8c, 0xda, 0x68, 0xcb, 0xa4, 0x88, 0x9b, 0x90, 0xef, 0x36, 0x7a, 0xbd, 0xf3, 0x0e,
	0x6d, 0x12, 0xc4, 0x02, 0xe4, 0x4e, 0x3a, 0x7d, 0x55, 0xa3, 0x17, 0xe4, 0x19, 0x02, 0x64, 0xa9,
	0x7c, 0xa6, 0x74, 0x54, 0xb2, 0xe3, 0x13, 0x4e, 0x14, 0xed, 0x82, 0xec, 0xfa, 0xaf, 0x3d, 0x8d,
	0xca, 0xb2, 0x46, 0x9e, 0xfb, 0xe4, 0xe3, 0xbe, 0xd2, 0x6a, 0x2a, 0xea, 0x19, 0x79, 0x0f, 0xb7,
	0x40, 0x6a, 0x74, 0x1b, 0x54, 0x6b, 0xcb, 0xaa, 0x46, 0x4a, 0x3e, 0x85, 0x76, 0x3a, 0x6d, 0xf2,
	0x3e, 0x16, 0x61, 0x4b, 0xfe, 0x59, 0xe9, 0x69, 0x8a, 0x7a, 0x36, 0xec, 0xf7, 0x64, 0x4a, 0xca,
	0xb8, 0x0b, 0xc5, 0xe5, 0x53, 0x97, 0x76, 0xba, 0x32, 0xd5, 0x2e, 0xc8, 0x0b, 0xdc, 0x06, 0xf0,
	0x01, 0xc3, 0x56, 0xe7, 0x4c, 0x51, 0xc9, 0x1e, 0x12, 0xd8, 0x3c, 0xed, 0xb7, 0x5a, 0xc3, 0x46,
	0xb3, 0x49, 0xe5, 0x5e, 0x8f, 0x7c, 0xf0, 0xf2, 0x35, 0xe4, 0xe3, 0x90, 0xe1, 0x0e, 0x90, 0x78,
	0xf8, 0x41, 0xa3, 0xa5, 0x34, 0xfd, 0x06, 0x9f, 0xf8, 0x63, 0x06, 0x37, 0x92, 0xf2, 0xc7, 0x51,
	0xd4, 0xf0, 0xb2, 0x71, 0xf0, 0x47, 0x1a, 0x9e, 0x0d, 0x12, 0x41, 0xe9, 0x31, 0xf7, 0xda, 0x34,
	0x18, 0xfe, 0x0a, 0x85, 0x44, 0x64, 0x70, 0xdd, 0xa5, 0x29, 0xaf, 0x9d, 0x3f, 0x34, 0x60, 0x33,
	0xb9, 0x55, 0xb8, 0xf6, 0x37, 0xab, 0xfc, 0xc9, 0xa3, 0x1a, 0x77, 0x96, 0xf4, 0x12, 0xb6, 0xef,
	0xa6, 0x0c, 0x3f, 0x7d, 0x94, 0xfc, 0x56, 0xfa, 0xcb, 0xaf, 0xd6, 0x44, 0x07, 0x62, 0xf3, 0xc8,
	0xca, 0xbb, 0xeb, 0x80, 0x5f, 0xac, 0x55, 0x23, 0xb9, 0x3a, 0xff, 0x49, 0xf6, 0xf8, 0x9b, 0x5f,
	0xbe, 0x9e, 0x9a, 0xc2, 0xd2, 0x47, 0x35, 0x7e, 0x29, 0xf4, 0xcf, 0x3c, 0x6e, 0xcd, 0x7d, 0xb0,
	0x57, 0x33, 0xf8, 0xac, 0x1e, 0xd7, 0xa9, 0x8f, 0x74, 0xe3, 0x92, 0xd9, 0xe3, 0x7a, 0xb2, 0xde,
	0x28, 0x1b, 0x7c, 0xb4, 0x0e, 0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x55, 0xdf, 0xfe, 0x61, 0xf0,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VerificationServiceClient is the client API for VerificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VerificationServiceClient interface {
	VerifyField(ctx context.Context, in *FieldDescription, opts ...grpc.CallOption) (*VerifyFieldResult, error)
	VerifyStruct(ctx context.Context, in *StructDescription, opts ...grpc.CallOption) (*VerifyStructResult, error)
	VerifyPostcode(ctx context.Context, in *VerifyPostcodeRequest, opts ...grpc.CallOption) (*VerifyPostcodeResult, error)
	VerifyPostcodeQuery(ctx context.Context, in *VerifyPostcodeQueryRequest, opts ...grpc.CallOption) (*VerifyPostcodeResult, error)
}

type verificationServiceClient struct {
	cc *grpc.ClientConn
}

func NewVerificationServiceClient(cc *grpc.ClientConn) VerificationServiceClient {
	return &verificationServiceClient{cc}
}

func (c *verificationServiceClient) VerifyField(ctx context.Context, in *FieldDescription, opts ...grpc.CallOption) (*VerifyFieldResult, error) {
	out := new(VerifyFieldResult)
	err := c.cc.Invoke(ctx, "/mashroom.verification.VerificationService/VerifyField", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationServiceClient) VerifyStruct(ctx context.Context, in *StructDescription, opts ...grpc.CallOption) (*VerifyStructResult, error) {
	out := new(VerifyStructResult)
	err := c.cc.Invoke(ctx, "/mashroom.verification.VerificationService/VerifyStruct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationServiceClient) VerifyPostcode(ctx context.Context, in *VerifyPostcodeRequest, opts ...grpc.CallOption) (*VerifyPostcodeResult, error) {
	out := new(VerifyPostcodeResult)
	err := c.cc.Invoke(ctx, "/mashroom.verification.VerificationService/VerifyPostcode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationServiceClient) VerifyPostcodeQuery(ctx context.Context, in *VerifyPostcodeQueryRequest, opts ...grpc.CallOption) (*VerifyPostcodeResult, error) {
	out := new(VerifyPostcodeResult)
	err := c.cc.Invoke(ctx, "/mashroom.verification.VerificationService/VerifyPostcodeQuery", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerificationServiceServer is the server API for VerificationService service.
type VerificationServiceServer interface {
	VerifyField(context.Context, *FieldDescription) (*VerifyFieldResult, error)
	VerifyStruct(context.Context, *StructDescription) (*VerifyStructResult, error)
	VerifyPostcode(context.Context, *VerifyPostcodeRequest) (*VerifyPostcodeResult, error)
	VerifyPostcodeQuery(context.Context, *VerifyPostcodeQueryRequest) (*VerifyPostcodeResult, error)
}

func RegisterVerificationServiceServer(s *grpc.Server, srv VerificationServiceServer) {
	s.RegisterService(&_VerificationService_serviceDesc, srv)
}

func _VerificationService_VerifyField_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FieldDescription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationServiceServer).VerifyField(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.verification.VerificationService/VerifyField",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationServiceServer).VerifyField(ctx, req.(*FieldDescription))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationService_VerifyStruct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StructDescription)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationServiceServer).VerifyStruct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.verification.VerificationService/VerifyStruct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationServiceServer).VerifyStruct(ctx, req.(*StructDescription))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationService_VerifyPostcode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPostcodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationServiceServer).VerifyPostcode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.verification.VerificationService/VerifyPostcode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationServiceServer).VerifyPostcode(ctx, req.(*VerifyPostcodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationService_VerifyPostcodeQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPostcodeQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationServiceServer).VerifyPostcodeQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mashroom.verification.VerificationService/VerifyPostcodeQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationServiceServer).VerifyPostcodeQuery(ctx, req.(*VerifyPostcodeQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VerificationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mashroom.verification.VerificationService",
	HandlerType: (*VerificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyField",
			Handler:    _VerificationService_VerifyField_Handler,
		},
		{
			MethodName: "VerifyStruct",
			Handler:    _VerificationService_VerifyStruct_Handler,
		},
		{
			MethodName: "VerifyPostcode",
			Handler:    _VerificationService_VerifyPostcode_Handler,
		},
		{
			MethodName: "VerifyPostcodeQuery",
			Handler:    _VerificationService_VerifyPostcodeQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
